### PR TITLE
Search

### PR DESCRIPTION
**Pull request by daanschipper**
The search bar is connected with Soundcloud, so you can use search terms like "Armin van Buuren".
Also the tracks from the search are nicely displayed as well as the recommended tracks.

### CODE REVIEW

**Comment by StefanBoodt** [comment]
Seems nice, makes it more easy to search as well. As usual very few problems are reported by the tools.

**Comment by StefanBoodt** [comment]
Sorry for the shortness, but there is not much else to say.

**Comment by Tomas2h** [comment]
Looks very nice.

I have only 1 question, was it intended to stack up all the search results when you search for another artist in the same instance of the page?

**Comment by ahovanesyan** [comment]
I like what you have done with the search bar but i think some changes need to be made before we merge this. When the user searches for multiple things the list should only contain the last search and not append. There should also be a way to clear the list without having to click anything, i recommend clearing the list when the search bar is used with an empty string.

**Comment by daanschipper** [comment]
I changed the things you guys noted, could you please review it again?

**Comment by ahovanesyan** [comment]
This works much better and exactly what i meant. Well done.

**Comment by Tomas2h** [comment]
Works perfect now, well done

**Comment by StefanBoodt** [comment]
I already agreed with the merge.

**Pull request merged**
