### PR TITLE
Tool tip

### PR DESCRIPTION
**Pull request by Tomas2h**
Instructions tool for the first time you visit the page.

### CODE REVIEW

**Comment by daanschipper** [comment]
The tooltips look good! Nice way to help a new user with our application.

I do not see why you've included another cookie library (the one from jQuery) when we already had one in our project. Is it possible to transfer the methods from one to the other?

Next, there is no need to merge the master into your branch if you do not rely on the changes made in the master. I see two unnecessary commits, which will only clog the commits. You have for instance merged the new css which makes the next and previous buttons twice so small, but not that they have been placed after eachother.

**Comment by Tomas2h** [comment]
Ill try to merge the 2 cookie files

I only merged so i could add the tooltip for the new buttons

**Comment by StefanBoodt** [comment]
The tour of the page seems nice. You can quit at any time using the skip button and it is really helpful. But I do not get the two merges with master at the commit list. That merge makes it more difficult to see what actually has been done on this branch while I do not see a point in this merge as no new content was used or altered.

**Comment by Tomas2h** [comment]
Merge the 2 cookie files would be a bit too much work for now since their code style is very different. So i decided not to do that.

**Comment by daanschipper** [comment]
Alright, I agree it would take a lot of time to combine the files. I approve the merge request.

**Pull request merged**
