### PR TITLE
Advanced slide menu

### PR DESCRIPTION
**Pull request by Tomas2h**
This branch containes slide menu for the application. The slide menu contains 2 features at this moment: The autoplay button and the numsplitter field which i took from another branch. Also did i adjust the tooltip function on the advanced menu.

### CODE REVIEW

**Comment by ahovanesyan** [comment]
I played with a couple of things and i think you should fix the following things before we merge this:
- When you narrow the page the advanced menu has a huge offset to the left. Align it to the buttons.
- The volume label looks weird and is not aligned with the volume slider. 
- When i enter bigger number of spits than the spitter can handle, it crashes.

**Comment by Tomas2h** [comment]
1) this works now
2) I reseted this one because this one won't fit
3) This is handled now by, if the number is too big then it takes the default amount of splits

**Comment by ahovanesyan** [comment]
Well done, the spits and the menu work very well now. It would be nice if the splits would be generated when a number of desired splits are set, but this is something we can add later. I approve the pr.

**Comment by daanschipper** [comment]
When the autoplay is on, I can't receive a preview of the song. When I pause the song, ask for a preview it only plays for one millisecond.
Further I can't the text on your button is very difficult to read, please use a text colour with more contrast.

**Comment by StefanBoodt** [comment]
The solution for way to many splits requested is done in a little bit of a hackish way. You simply altered the code to do the default instead. You do not even alert the user of his mistake.

What happens when the splits does not occur in the JSON? Or if it is not a number. For instance when the user did not fill the box with any value. The String "" does not match any numbers. But then this last one is fixed in the javascript of the page.

The following code is a little duplicate, because 2 out of 3 paths set the value from 0 to 0. There is also the indentation issue (again) :

var message = {
             "track": sounds[0],
-            "waveform": waveform.data
-            "waveform": waveform.data,
-            "splits" : 0
       };
-        if($("#numsplit").val() == '' ) {
-            message["splits"] =  0;
-        }else if(parseInt($("#numsplit").val()) > 0){
-            message["splits"] =  parseInt($("#numsplit").val());
-        }else{
-            message["splits"] = 0;
-            console.log("Number of splits must be greater or equal than zero");
-        }

My knowledge of javascript may not be extremely high but if "#numsplit" does not contain a number than the result of the parseInt is undefined. Then undefined is stored in the JSON message and then we encounter the point I already made.

**Pull request closed without merging**
