### PR TITLE
Advanced slide menu

### PR DESCRIPTION
**Pull request by Tomas2h**
Changed the preview bug and the numsplit input now gives a warning when something wrong is given

### CODE REVIEW

**Comment by StefanBoodt** [comment]
I already said it on the old PR but there now is even more duplicate code in controls.js. 2 out of the three paths do mostly the same and the code is simply copy pasted. You also change the value from 0 to 0 in two of the branches.

Additionally there is still bad indentation in the file. There should be a space on both sides of the () in an if statement, while loop and for loop.

The code also does still have the issue with: List<Integer> splits = splitter.split(json.get("splits").asInt()); as javadoc can send undefined for message["splits"] =  parseInt($("#numsplit").val());. In case you did not know this causes some weird behaviour. Check the value of numsplit before you send it.

These points are nothing new because I already wrote them this morning and there has been no improvement in them.

**Comment by Tomas2h** [comment]
Changed the indentation errors and removed some of the duplication.

**Comment by daanschipper** [comment]
I could only find that when I spam the menu it behaves strangely and that when I'm entering an absurdly high number I receive only 20 splits.

You should include the new mode selector in the main in the advanced menu though when you're merging with the master.

I approve the pull request

**Comment by StefanBoodt** [comment]
I still see some duplicates. But at least the undefined is now handled. Is split always defined in the JSON or can it in any way go wrong here? Or elsewhere after merging.

**Pull request merged**
