### PR TITLE
Algorithm Selector

### PR DESCRIPTION
**Pull request by daanschipper**
First the CommentIntensitySeeker seeks for a start of the snippet. If this fails a random start will be chosen.

### CODE REVIEW

**Comment by ahovanesyan** [comment]
The AlgorithmSelector seems to be working fine. The application class still has a couple of variables that are not used, but since we haven't fully switched to Track objects instead of track-id's i guess we don't need to remove them yet. Something to keep in mind when we release tomorrow.

**Comment by StefanBoodt** [comment]
This pull request introduces new PMD errors as well as new CheckStyle errors. FindBugs also has some complaints. I know some of these are because of the fact this branch was created from a branch other than master, but there are some of these that are actually important. There are also a lot of simple CheckStyle errors that occur in this branch, that have something to do with bad javadocs.

The two FindBugs bugs in the Application class are caused by this branch.

If you can remove some CheckStyle errors and fix the two FindBugs bugs in Application you have my support for the merge. Until then you do not.

**Comment by StefanBoodt** [comment]
The bugs are removed. CheckStyle now has way less errors. There still are two PMD errors left, both are unused private methods.

However the TrackProcess still has a name that starts with an uppercase. Further this branch seems fine.

Why is there a duplicate getStartTime method in Application. Can't we just rewrite the getStartTime(int trackid) to getStartTime(Track)?

**Comment by daanschipper** [comment]
The two unused methods are for future extension. TrackProcess() is not my method, I have no idea where this get called from. @ahovanesyan Can you look into this. 
I left the old method in its place since some other methods rely on that. I did not want to break stuff accidentally.

**Pull request merged**
