### PR TITLE
Seeker refactoring to include the Decorator design pattern and making the MixSeeker work.

### PR DESCRIPTION
**Pull request by StefanBoodt**
Also contains small updates on the Seeker interfaces and in some tests especially for the Seeker classes. Also the models.score package now has some classes that make comparing and mixing scores easier. The CommentIntensitySeeker is now more efficient as well because it calls the calculating methods less and now uses a sort and than checks instead of using logarithmical search.

### CODE REVIEW

**Comment by StefanBoodt** [comment]
Everything was fine until suddenly everything went bad. I shall remove the Travis error.

**Comment by StefanBoodt** [comment]
Earlier Travis fails were because Travis does not support Java 8 or because a PMD error was found, and wrongly fixed, during execution. This PMD error, calling a variable from an enclosing class, did not show up during our own maven site and did not make any sense. But it is fixed now regardless.

**Comment by Tomas2h** [comment]
Very nice improvement of the Seeker package. The fact that it is now remade with the decorator design pattern, gives it a good look. I think Bachelli would love it

**Comment by daanschipper** [comment]
Very well done! The plugins do not report anything wrong in your code.

**Pull request merged**
