### PR TITLE
Number of splits

### PR DESCRIPTION
**Pull request by Tomas2h**
This is a extra feature to choose the amount of mix splits that you want when pressing mixsplitter

### CODE REVIEW

**Comment by daanschipper** [comment]
Again, there is no need to merge the master into your branch. It just makes it unclear for us to review, for instance you have not merged properly and files like app/controllers/Application.java.orig are also included in your commit. Please fix these added files.

Next I still found some CheckStyle errors for the small additions you have done to controllers.Application, which suggest that you did not even checked the plugins before requesting this pull. 

Please make sure you're code is up to the standards we all agreed upon.

**Comment by daanschipper** [comment]
The user can now enter in how many pieces a mix should be split to. No errors generated by the plugins.

Only note I can make is that the splitWaveform() and nSplitWaveform() are exactly the same, I would have preferred to see some clever way of combining these methods, but for now this is fine since we don't know yet how we will use this further.

**Comment by StefanBoodt** [comment]
I honestly disagree with Daan. I do not think that duplication is good. Please put the following in a method
-            Map<String, List<Integer>> map = new TreeMap<String, List<Integer>>();
-            map.put("response", list);
-            JsonNode response = mapper.valueToTree(map);
-            return ok(response);

and call it from two different methods. The split should be different for both methods but that is for later.

Second the message of "Keep the box empty for the default amount of splits" is incorrect. If the box is empty we should run the version without limit.

Third I highly disagree on merging an incomplete branch. You altered the GUI for a function that does not yet exist. This is confusing for us and any user that uses the System. Please alter the Splitter Interface and include a splitter(int n) method. Fixing this method is not your job it is mine, but I suggest you do not include new functions in the GUI that result in nothing new. Even a default implementation of the method would do, such as one that checks if the number is smaller than the size and does sublist when it is. Then test this method and you have written more code and your GUI function does something new. This is also good for your personal report.

For now I reject this request.

**Comment by ahovanesyan** [comment]
Just like Daan i don't agree with the fact that the two methods are duplicates of each other. There is no reason to make two separate methods for this. I think its possible to just use one method. Also you pass a String to a method that should take an amount of splits (int). Parsing the data to the right types and making sure that the user can't pass anything else than an integer above 0 should be something that should be processed locally and not sent first. Putting constraints might not be necessary right now but should definitely done in the future. I have mixed feelings about this and i think that a third person should review this first before its ready to merge.

**Pull request closed without merging**
