### PR TITLE
Track processor

### PR DESCRIPTION
**Pull request by daanschipper**
Class to process .track files. Code is up to the standards of the product planning as regards to checkstyle, pmd and findbugs. Since the only purpose of this code is to process the .track files and upload them to the database and all the .track files are successfully uploaded to the database it is not needed to test the code. I also updated the tests for the DatabaseController and CommentRetriever classes.

### CODE REVIEW

**Comment by StefanBoodt** [comment]
There seems to be some unfinished code in the commit, since Reader.readLine is an empty method, which is probably because you put it in the database here, but that is to be guessed in its entirety.

Second you have the @SuppressWarnings("unused") on top of your class. I appreciate the use of these kinds of tags when necessary but I highly doubt it is necessary here. Please follow the convention, and best practice, of the rule and put it over the smallest piece of code possible, which is, according to me, not the class.

Third the new return of a boolean in some methods is done in a very clumsy way. Doing it this way results in higher cyclomatic complexity and the need for more tests. You can simplify here.

Further the new code seems to be entirely untested by unit tests and contains a lot of private methods. This is bad practice. Consider using the protected modifier here and think of ways to test the code more, such as making the methods protected or by removing any hardcoded connections to the database so you can reroute them. 

PMD found a new error in the way of an empty catch block on this branch. Please think of whether or not this is the wanted result again. Do you really not want to let an user know something went wrong.

Finally you use System.out.println() in TrackProcessor to report an error. Please remember that there is a System.err.println() as well to print errors.

Please fix some of these errors before continuing with this pull request.

**Comment by daanschipper** [comment]
1) Reader.readline() is a stub method, so that a subclass can override this method.
2) It is only necessary to process the track once, after that this code isn't used. I included the suppress warning so we won't have the warning present.
3) I returned a boolean to verify that an exception has been caught
4) See the first comment as why I didn't test the TrackProcessor class

The last two items I'll fix

**Comment by StefanBoodt** [comment]
1) I see, you use a hook design here. Sorry I did not recognize it for a moment.
2) I still think that the error is only thrown on private things as public and protected things are usually capable of being called from elsewhere in the code. But you said IntelliJ used it differently for some reason.
3) I know. But you did the same on requesting an empty query. Doing so created two separate paths that where 100% the same.
4) Some methods such as convert boolean are still useful to test and do not require database connection. I thought specifically about testing them.

**Comment by StefanBoodt** [comment]
Seems a lot better. The code is a little more simple and there is no unnecessary code on the path since the empty String would always give an SQL exception and thus a duplicate path is removed. Since the empty catch block is removed PMD is much more pleased. You might want to explain the not testing in the test report, which we currently do not yet have.Further the code seems nice.

**Comment by ahovanesyan** [comment]
I like what you've done with the reader and don't see any reason not to merge this branch. This might be a slight pain because the amount of commits made to master after the branch creation.

**Pull request merged**
