### PR TITLE
Recommender

### PR DESCRIPTION
**Pull request by daanschipper**
The user can now receive recommended songs based on his liked songs. The liked songs are saved to the users profile, these likes are only saved for the current session.

Also the Track object is now a map, where entries can be dynamically added and requested, instead of pre defined variables. Because of this change some classes we're redundant and thus removed from the application.

I included a filter for FindBugs to exclude the standard errors generated by de files of the Play Framework.

### CODE REVIEW

**Comment by Tomas2h** [comment]
It works very nice and the overall code looks also good, well done.

**Comment by StefanBoodt** [comment]
Looks really good! There are a few (negative) remarks, worth mentioning however.

(1) Why is the Magic Numbers test removed?

(2) Why is mode being done this way? It now is way harder to add a extra mode to it.

(3) The java enum values are actually classes. What you did here therefore is reducible to if (mode == 1) else if (mode == 2)... while the enum is more powerful and could do mode.select.

(4) Why does the algorithm selector still return an int. Changing it to a timedsnippet makes it easily way more dynamic since it can then handle different durations. The seekers have supported this since the very beginning.

(5) The nice JSON class still is not used. You inserted new duplicate code that simply reads the JSON for the track data.

(6) Why is it that I can not find 1 recommend test that is not commented out? Did you test it with unit tests on a reasonable scale/level.

(7) This branch is so far behind that a lot of improvements over the last few weeks are missing. There is a huge merge conflict here. In fact it is so huge that, a lot of bad practice that has been removed has gotten worse in this branch. I urge you to start merging already and try to get the PR after the merge on this branch, as it removes all the crap from this branch and allows everyone to see what you actually did. Instead of trying the pr on a branch that has bad style because it was not yet fixed when the branch was created.

(8) Why did you alter the track class in the way you did. It is not entirely common to use a map to store all the variables of a class. In fact it is quite bad. You introduced a new way to make relatively easy mistakes and created the new class in such a way that every class has to be modified if you decide to name the variable different. Point this leads to a high likelihood of coding errors on a very short timescale.

(9) There has been HTML code inserted that contains a style part in the tag. HTML should be free of every possible style tag as the style is not the HTML task. Use css instead. This also has to do with the MVC architecture of our project. Found this in main.scala.html.

(10) A lot of methods are incredebly long and/or contain additional lines such as increasing a counter and setting a boolean to true and then checking if this boolean is true while checking if the counter is 0, results in the same thing. Please make some of the methods a little smaller.

(11) Make sure every method has only one javadoc explaining it. Two javadocs on one method is confusing. Please remove one of them in the Record class at the hashCode method.

I know this may seem like a lot of criticism but keep in mind that your added almost 2000 lines. For the most part an excellent job has been done on them. You even managed to remove the findBugs errors.

**Comment by daanschipper** [comment]
I've adjusted most of your points, you can read a detailed description of each point below. I'll retry the pull request.

(1) We all know this is bad practice and avoid it. But for instance when you need 25% of the weight to add to your score, you need to declare a final static double, set it to 0.25 and use that variable. In my opinion this is even worse. We didn't use a magic number anywhere else.
(2, 3) @ahovanesyan already discussed these during the daily meeting with you
(4) No idea why that was still the case, but I changed it anyway.
(5) This is (partially) resolved now. Only the splitwaveform method needs to be adjusted still, but I don't know the details about this method and I don't want to break the application
(6) There were indeed some commented out test, @ahovanesyan provided more test for our classes.
(7) We specifically didn't merge so the changes were clearly visible. But you're right that this branch was far behind, I've merged the master in this branch and tested all functions.
(8) This is discussed during the meeting and adjusted accordingly.
(9) I forgot to remove this from the HTML and transfer it to the CSS.
(10) The concerning methods have been adjusted
(11) Small error that we have overlooked.

**Comment by Tomas2h** [comment]
It is now even better than before with a lot of testing which will increase our test coverage, well done

**Comment by StefanBoodt** [comment]
The overall code looks fine. I only have 3 issues. If further everything works it is perfectly fine.

(1) The same as (1) last time. We should write it in the CheckStyle document in the docs repository.

(2) I noticed that all the occurrences of the id have been changed to ID, this is also the case for any other default variable in the track class. While this is fine for all the javadoc comments, the id already has the disadvantage that is in the HTML as well. Since most browsers can handle faulty HTML code this is not all to bad, but there are a few that might not be able to handle it. As such we should change the ID in the HTML back to the correct id.

(3) While I am pretty sure that it is handled did anyone test the mix splitter in this branch? This is simply a question because every other button on the GUI has been demolished by this branch and therefore I can not believe that this one is working.

This branch contains a lot of new features that are really necessary for the project. It also features nice outcome of the tooling as a lot of code has been added and a lot of untested code has been removed. It also now has all those nasty FindBugs errors that were created by the generated classes resolved by excluding them. This merge has my acceptance.

**Comment by StefanBoodt** [comment]
I forgot to mention the fact that the Track.equals and Track.compareTo still create their own keys, which are identical to the static keys in the class. I saw some test classes do something similar as well.

**Comment by daanschipper** [comment]
(1) I'll add this to the test report
(2) This happened by accident, reverted it
(3) I tested this, it works. The bug where the splits from a previous songs are still present is not fixed though.
(4) Track uses the static keys now. It doesn't matter that the test use other keys.

**Comment by daanschipper** [comment]
@ahovanesyan is still testing some classes

**Pull request merged**
