### PR TITLE
Xml score is now useable

### PR DESCRIPTION
**Pull request by StefanBoodt**
This branch includes the feature to use XML files instead of having a hard-coded array of words with the values and format. This allows for much more dynamism and allows us even to change it at runtime by allowing everyone to refer to another file. However that cannot be done by this branch, but this branch does allow the creation of the data from another file, just not in a way a user can send in it's own file because it does not alter the GUI.

The usage of allowing XML files and doing everything with as backend the ScoreParser interface even allows the creation of new parsers for other datasources, such as JSON files or databases, and then being capable of plugging in the result into the existing code, all by simply implementing the interface.

### CODE REVIEW

**Comment by daanschipper** [comment]
Overal this looks like a solid improvement to look at the content of the comments.
I have only two questions:
1) Why have you included the class InvalidXMLFormatException in the XMLScoreParser class and not just used a separate package for errors?
2) The method XMLScoreParser.getScore() is quite vague to me when I was looking at it. Is it possible to add some comments or split the method up into separate methods with descriptive names?

**Comment by StefanBoodt** [comment]
1) I can alter that but the XMLFormatException is only for invalid XML format. Since we only have one class that uses XML formats it simply wastes another package to put it in a package on it's own. Especially when that package containing only one package is then referenced by only this class. Creating this package is a little bit of an overkill, and also makes everything more difficult to comprehend since you then have to search more packages and classes for a package with only 1 class that is only referenced at one point in the code.

2) The method you are referring to does not exist. You probably mean the getScores() method. Splitting this method further is quite simply put not useful. Doing this will cause some serious overhead for the method execution, since we keep copying the variables we already extracted and the system we already build and the new system will also be unnecessary copied.  Half of this method is actually checks to see if the file is valid enough to produce a certain outcome. By which I mean it checks only if the file is good enough to produce a deterministic outcome. I shall put the two checks in the middle in a separate method because it pleases you but further splitting will simply make the algorithm less readable. This simply is the way you read XML files using a DOM parser. I can however include some more comments.

**Comment by ahovanesyan** [comment]
The code looks very slick overall and the explanation in the comments is clear. The getScores method seems bigger than the advised method size. But looking at what you've just said i understand why splitting the method might do more bad than good. Nonetheless i like what you've done here and i support the merge.

**Comment by daanschipper** [comment]
If you can add some supporting comments or split up the getScores() method as you suggested I'll support the merge.

**Comment by StefanBoodt** [comment]
Fixed the commented issues. Please rereview the changed part.

**Comment by daanschipper** [comment]
Perfect, you've done what I've asked for.

**Pull request merged**
