### PR TITLE
Database Integration

### PR DESCRIPTION
**Pull request by daanschipper**
This is the code to connect to the comments in the database that is hosted on a remote server. I've added a Global class that runs on the start and end of the play application to make a connection to the database and close it on the end. The code to parse all the .comment files is also included, although it is not used anymore. Further I've added a class to retrieve the comments from a database, this can be extended in the future if more methods are needed.

### CODE REVIEW

**Comment by StefanBoodt** [comment]
When importing this into Eclipse I noticed there where parser problems with the Feature Processor. When I told you this during the daily meeting you told me that, that was by accident as it was still being worked on. Due to the parser errors that are present it is not possible to allow it to be merged at this point in time.

On the other hand the code seems nice and readable, with javadoc on most of the methods and a lot of useful methods. But some methods are missing {at}param or {at}return such as the constructor of the comment processor class. Please fix the parser errors before it can be more explicitly reviewed.

**Comment by ahovanesyan** [comment]
Looks fine overall. We should add some more javadoc in classes that are a bit unclear. CommentRetrieverTest shows an error for me, not sure if there exists a makeConnection(null) method for comment retriever.

**Comment by ahovanesyan** [comment]
The problems i encountered the previous commit are now fixed thanks to last one.

**Comment by StefanBoodt** [comment]
I have made the following notes regarding the PR.

The Global class seems to contain no comments.

The database connector is tested by only 55% for some reason but this reason is not explained anywhere.

FindBugs reports that a bug is found in the comment processor.readFolder method.

Maven site reported the following : [WARNING] The repository url 'http://scala-tools.org/repo-releases/' is invalid - Repository 'ScalaToolsMaven2Repository' will be blacklisted.
and then stops.

Code further seems fine, and maven tells that all tests are passing. It contains some large improvements to the database structure and is way more dynamic than the previous one. Further the new version is logged which will help greatly during testing and debugging.

**Comment by StefanBoodt** [comment]
In case I was not clear about this, I simply noted these things. A lot of changes have been going on in this branch and despite the large amount of things that are not perfect, there is to be noted that they also were present before the branch was created.

On top of that the code in this branch seems to be actually working way better than the previous code. The pom is nicely updated and actually contains some stuff now.

Despite the fact that we are not quite there yet, this piece contains so many necessary updates that I think it should be merged regardless. This is especially true since we are already forming two master branches on the repo right now and the working database is really important to build the rest of the project on. So I am hugely in favor of merging it with the master branch.

**Comment by StefanBoodt** [comment]
I see. This is way better to merge already. I again state my support.

**Pull request merged**
